[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "pnpm build"

[[redirects]]
  from = "/api/newsletter/*"
  to = "/.netlify/functions/newsletter"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

